### ISSUE TITLE
Link to documentation not working

### ISSUE THREAD

**Issue by tobiaslauxtermann** [wago-enterprise-education/vscode-wago-cc100#3]
The button to the documentation does not link to the public GitHub repository.

**Comment by maikrehburg** [comment]
- link is pointing to external repo readme.md
- simple browser seems broken, use external browser

**Comment by andrebell** [comment]
It seams as if SimpleBrowser cannot be used, since github.com does not allow embedding:

- https://github.com/microsoft/vscode/issues/146656#issuecomment-1088037400
- https://github.com/microsoft/vscode/issues/157889
